### ISSUE TITLE
New maintainer - I'll put my hand up

### ISSUE THREAD

**Issue by chrisk-7777** [drcmda/react-zdog#29]
Hi @drcmda , I saw you mention on Twitter you were, possibly, looking for a new maintainer? 

I'd be happy to take it on, especially considering the small surface area. I already help out around other parts of pmndrs, in particular the Zustand docs.

**Comment by bhushan6** [comment]
Hi @chrisk-7777 , I got access of this package from paul and I'll be maintaining it. But of course any help to maintain will be great since I don't have any experience working with open source projects. We can discuss about this on discord if you are free. Please DM me on discord (bhushanw.tf#4832) or let me know your discord handle. Looking forward to connect with you.

**Comment by chrisk-7777** [comment]
Sounds good! 

Maybe its easier to keep the discussion here on Github though? In the repo settings, there should be an option to enable "Discussions". That way everyone can see the conversation and contribute without needing Discord. 

Eitherway, I'll close this issue
